tf-repo-mgmt/repository-meta-data/meta-data.csv

This PR adds metadata for the avm-ptn-aiml-ai-foundry module.

chore: add avm-ptn-aiml-ai-foundry metadata

---

tf-repo-mgmt/repository-meta-data/meta-data.csv

This PR adds metadata for the avm-res-network-serviceendpointpolicy module.

chore: add avm-res-network-serviceendpointpolicy metadata

---

tf-repo-mgmt/repository-meta-data/meta-data.csv

This PR adds metadata for the avm-res-insights-privatelinkscope module.

chore: add avm-res-insights-privatelinkscope metadata

---

tf-repo-mgmt/repository-meta-data/meta-data.csv

This PR adds metadata for the avm-res-hybridcompute-machine module.

chore: add avm-res-hybridcompute-machine metadata

---

tf-repo-mgmt/repository-meta-data/meta-data.csv

This PR adds metadata for the avm-res-alertsmanagement-actionrule module.

chore: add avm-res-alertsmanagement-actionrule metadata

---

tf-repo-mgmt/repository-meta-data/meta-data.csv

This PR adds metadata for the avm-res-containerservice-fleets module.

chore: add avm-res-containerservice-fleets metadata

---

tf-repo-mgmt/repository-meta-data/meta-data.csv

This PR adds metadata for the avm-res-iotoperations-instance module.

chore: add avm-res-iotoperations-instance metadata

---

tf-repo-mgmt/repository-meta-data/meta-data.csv

This PR adds metadata for the avm-res-insights-metricalert module.

chore: add avm-res-insights-metricalert metadata

---

tf-repo-mgmt/repository-meta-data/meta-data.csv

This PR adds metadata for the avm-res-certificateregistration-certificateorder module.

chore: add avm-res-certificateregistration-certificateorder metadata

---

.github/workflows/managed-pr-check.yml
tf-repo-mgmt/repository_sync/github.rulesets.tf
tf-repo-mgmt/repository_sync/github.tf
tf-repo-mgmt/repository_sync/variables.tf

One side-effect of enabling the environment in the subject claim is that every job in that workflow needs and environment set, otherwise GitHub cannot start it.
This adds a dummy environment that has no secrets & that requries no approval.

feat: create dummy environment for jobs not requiring auth

---

.github/workflows/housekeeping-pr-cleanup.yml
porch-configs/pr-check.porch.yaml

Adds in a avmfix step after mapotf transform, to ensure that the code formatting is correct and avoid a diff error on the pr-check workflow.
Tested in a module locally using `AVM_PORCH_REF` to use polices from this branch and works well.
Also finally sort out the housekeeping workflow

fix(porch): pr-check

---

tflint-configs/avm.tflint.hcl
tflint-configs/avm.tflint_example.hcl
tflint-configs/avm.tflint_module.hcl

Add the `exact = true` property to the `terraform_module_version` rule from tflint to enforce TFFR1
See: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/main/docs/rules/terraform_module_version.md

feat: enforce tffr1 version exact check

---

Makefile
tests/terraform-azure-avm-res-mock/.devcontainer/devcontainer.json
tests/terraform-azure-avm-res-mock/main.telemetry.tf
tests/terraform-azurerm-avm-res-mock/.devcontainer/devcontainer.json
tests/terraform-azurerm-avm-res-mock/main.telemetry.tf

This pull request adds a new `migrate` target to the `Makefile`. The target is a no-op, indicating that the repository has already been migrated.

feat(makefile): migrate target as no-op

---

.github/workflows/governance-test.yml
porch-configs/pre-commit.porch.yaml
tests/terraform-azure-avm-res-mock/main.telemetry.tf
tests/terraform-azurerm-avm-res-mock/main.telemetry.tf

This pull request adds a new pre-commit command to install Terraform using `tfenv` in the `porch-configs/pre-commit.porch.yaml` file. 
This prevents a race condition where multiple parallel jobs are trying to do the same thing.
Key change:
* Added a new shell command (`install Terraform`) that checks the Terraform version, ensuring Terraform is installed and ready for use during pre-commit checks.
- Improved Trivy output on container build

fix: prevent race condition in pre-commit by installing Terraform before parallel job

---

porch-configs/pr-check.porch.yaml
porch-configs/pre-commit.porch.yaml

This pull request modifies the execution mode and structure of commands in `porch-configs/pr-check.porch.yaml` and `porch-configs/pre-commit.porch.yaml` to ensure sequential processing. The changes primarily involve switching from parallel to serial execution for specific command groups and subcommands.
Execution mode changes in `porch-configs/pr-check.porch.yaml`:
* Changed the `type` of the `avmfix` command group from `parallel` to `serial`.  
* Updated the `mode` of the `submodules` command from `parallel` to `serial`.  
* Updated the `mode` of the `examples` command from `parallel` to `serial`.  
Execution mode changes in `porch-configs/pre-commit.porch.yaml`:
* Changed the `type` of the `avmfix` command group from `parallel` to `serial`.  
* Updated the `mode` of the `submodules` …

fix: pre-commit & pr-check avmfix must be run serially

---

tf-repo-mgmt/repository-meta-data/meta-data.csv

This PR adds metadata for the avm-res-documentdb-mongocluster module.

chore: add avm-res-documentdb-mongocluster metadata

---

tf-repo-mgmt/repository-meta-data/meta-data.csv

This PR adds metadata for the avm-ptn-aca-lza-hosting-environment module.

chore: add avm-ptn-aca-lza-hosting-environment metadata

---

tf-repo-mgmt/repository-meta-data/meta-data.csv

This PR adds metadata for the avm-res-compute-capacityreservationgroup module.

chore: add avm-res-compute-capacityreservationgroup metadata

---

managed-files/root/avm

Mount /var/run/docker.sock into the container when CONTAINER_RUNTIME=docker so containerized tasks can access the host Docker daemon. Only applies when the socket exists on the host.

feat(avm): mount host docker socket when using docker runtime

---

Makefile
managed-files/root/avm
managed-files/root/avm.ps1

This pull request introduces improvements to both the developer experience and the flexibility of the AVM Porch tooling. The most significant changes are the addition of environment variable overrides for TUI (Text User Interface) mode and enhancements to the `Makefile` help output. These updates make it easier to control interactive behavior in different environments and clarify available `make` targets for users.
**TUI Behavior Overrides:**
* Added support for `PORCH_FORCE_TUI` and `PORCH_NO_TUI` environment variables in both `managed-files/root/avm` (bash) and `managed-files/root/avm.ps1` (PowerShell) scripts. This allows users to explicitly enable or disable TUI mode regardless of CI environment or color settings. (`[[1]](diffhunk://#diff-98bc6d99ffee2a9c5f3329e875c473e1e32dd1c8a580e3c …

feat: porch TUI flags plus makefile help

---

.github/workflows/legacy-container-test.yml
container/Dockerfile.azterraform
tests/terraform-azure-avm-res-mock/.devcontainer/devcontainer.json
tests/terraform-azurerm-avm-res-mock/.devcontainer/devcontainer.json

This pull request introduces a new GitHub Actions workflow for legacy container testing and makes a minor update to the container build configuration. The workflow automates the building and vulnerability scanning of the container image, improving CI coverage and security checks for changes in the `container` directory.
**CI Workflow Additions:**
* Added `.github/workflows/legacy-container-test.yml` to automate building the azterraform container image, running Trivy vulnerability scans, and publishing scan results for pull requests affecting the `container` directory.
**Build Configuration Update:**
* Set `CGO_ENABLED=1` in `container/Dockerfile.azterraform` to enable CGO during Go builds, which may be required for certain dependencies or features.

fix(container): cgo for legacy build

---

.github/workflows/admin-merge-pre-commit-prs.yml
.github/workflows/pre-commit-cron.yml

This pull request updates the GitHub Actions workflows related to pre-commit pull requests, focusing on improving the automation and permissions for merging PRs. The main changes include renaming a workflow for clarity, adjusting merge commands to better use admin privileges, and refining environment and error handling in the scripts.
**Workflow and automation improvements:**
* Renamed the workflow from `pre-commit-cron` to `admin-merge-pre-commit-prs` in `.github/workflows/admin-merge-pre-commit-prs.yml` for clearer identification of its purpose.
**Merge command and permissions adjustments:**
* Removed the redundant `--merge` flag from the `gh pr merge` command in `.github/workflows/admin-merge-pre-commit-prs.yml`, ensuring only the `--squash` merge method is used.
* In …

ci: fix admin pre-commit command

---

tf-repo-mgmt/repository-meta-data/meta-data.csv

This PR adds metadata for the avm-res-virtualmachineimages-imagetemplate module.

chore: add avm-res-virtualmachineimages-imagetemplate metadata
